namespace Pulp.Pulpifier.Tests;

[TestClass]
public class CompilerTests {
	[TestMethod]
	[DataRow("Foo\n", "Foo\n\n")]
	[DataRow("Foo Bar\n", "Foo Bar\n\n")]
	[DataRow("Foo. Bar.\n", "Foo.\n\n\nBar.\n\n")]
	[DataRow("Foo! Bar.\n", "Foo!\n\n\nBar.\n\n")]
	[DataRow("Foo? Bar.\n", "Foo?\n\n\nBar.\n\n")]
	[DataRow("“Foo! Bar.”\n", "“Foo!”\n\n\n“Bar.”\n\n")]
	[DataRow("“Foo? Bar.”\n", "“Foo?”\n\n\n“Bar.”\n\n")]
	[DataRow("Foo— Bar.\n", "Foo—\n\n\nBar.\n\n")]
	[DataRow("Foo; Bar.\n", "Foo;\n\n\nBar.\n\n")]
	[DataRow("*Foo*. Bar.\n", "*Foo*.\n\n\nBar.\n\n")]
	[DataRow("(Foo.) Bar.\n", "(Foo.)\n\n\nBar.\n\n")]
	[DataRow("\"'Foo.'\" Bar.\n", "\"'Foo.'\"\n\n\nBar.\n\n")]
	[DataRow("Foo, “Bar.”\n", "Foo,\n\n\n“Bar.”\n\n")]
	[DataRow("Foo, \"Bar.\"\n", "Foo,\n\n\n\"Bar.\"\n\n")]
	[DataRow("Foo, Bar.\n", "Foo,\nd=joined\n\nBar.\n\n")]
	[DataRow("Foo, Bar.\n", "Foo,\nd=joined\n\nBar.\nd=\n")]
	[DataRow("Foo. Bar\n", "Foo. <e>lorem</e>Bar\n\n")]
	[DataRow("Foo Bar\n", "<e>lorem</e>Foo Bar<e>ipsum</e>\n\n")]
	[DataRow("Foo Bar\n", "<e>lorem</e>Foo <e>mid</e>Bar<e>ipsum</e>\n\n")]
	[DataRow("Foo. Bar.\n", "<e>1</e>Foo.<e>2</e> <e>3</e>Bar.<e>4</e><e>5</e>\n\n")]
	[DataRow("Foo. Bar.\n", "<e>1</e>Foo.<e>2</e>\n\n\n<e>3</e>Bar.<e>4</e><e>5</e>\n\n")]
	[DataRow("Foo. Bar.\n", "<e>1</e>Foo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e><e>5</e>\n\n")]
	[DataRow("Foo. Bar.\n", "<e>1</e>\n\n\nFoo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e>\n\n\n<e>5</e>\n\n")]
	[DataRow("Foo\n\nFizz\n\nBuzz\n", "Foo\n\n\nFizz\n\n\nBuzz\n\n")]
	[DataRow("\"Foo\"\n", "\"Foo\"\n\n")]
	[DataRow("\"Foo\" foo Foo. \"Foo.\"\n", "\"Foo\" foo Foo. \"Foo.\"\n\n")]
	[DataRow("\"Foo\" foo Foo. \"Foo.\"\n", "\"Foo\" foo Foo.\n\n\n\"Foo.\"\n\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\n\n\n\"Bar.\"\n\n")]
	[DataRow("“Foo. Bar.”\n", "“Foo.”\n\n\n“Bar.”\n\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\n\n\n<e>edit</e>\n\n\n\"Bar.\"\n\n")]
	[DataRow("“Foo. Bar.”\n", "“Foo.”\n\n\n<e>edit</e>\n\n\n“Bar.”\n\n")]
	[DataRow("\"Foo. Bar. Foobar.\"\n", "\"Foo.\"\n\n\n\"Bar.\"\n\n\n\"Foobar.\"\n\n")]
	[DataRow("\"Foo. Bar.\n\n\"Fizz. Buzz.\"\n", "\"Foo. Bar.\"\n\n\n\"Fizz. Buzz.\"\n\n")]
	[DataRow("\"Foo. Bar.\n\n\"Fizz. Buzz.\"\n", "\"Foo.\"\n\n\n\"Bar.\"\n\n\n\"Fizz.\"\n\n\n\"Buzz.\"\n\n")]
	[DataRow("Foo.\n\nBar.\n", "Foo.\n\n\n<e>Text</e>\n\n\nBar.\n\n")]
	[DataRow("Foo. Fizz\n\nBuzz\n", "Foo.\n\n\nFizz\n\n\nBuzz\n\n")]
	[DataRow("Foo. Fizz\n\nBuzz\n", "Foo.<e>lorem</e>\n\n\nFizz<e>ipsum</e>\n\n\nBuzz\n\n")]
	[DataRow("Foo\n", "Foo\nb=back\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=!foo\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;n:bar=Bar;c=foo,bar\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;n:bar=Bar;c=foo,,bar\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;n:bar=Bar;c=,foo,,bar,\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\nn:foo=FOO\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo;c=foo\n\nBar\nc=\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\nc=foo\n")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:f=foo;s=f\n")]
	[DataRow("Foo\n", "Foo\nn:f=foo;t=f\n")]
	[DataRow("Foo\n\n\"Bar\"\n", "Foo\nn:foo=Foo\n\n\"Bar\"\ns=foo\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\nt=foo\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\ne:foo=boo\n")]
	[DataRow("Foo\n\n\"Bar\"\n", "Foo\nn:foo=Foo\n\n\"Bar\"\ns=foo;c=foo;e:foo=boo\n")]
	[DataRow("Foo\n\n“Bar”\n", "Foo\nn:foo=Foo\n\n“Bar”\ns=foo;c=foo;e:foo=boo\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\nt=foo;c=foo;e:foo=boo\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\na:foo=24\n")]
	[DataRow("Foo\n\n\"Bar\"\n", "Foo\nn:foo=Foo\n\n\"Bar\"\ns=foo;c=foo;a:foo=old\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\nt=foo;c=foo;a:foo=old\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\nx:foo=tie\n")]
	[DataRow("Foo\n", "Foo\nn:f=F;c=f;e:f=hip;a:f=99\n")]
	[DataRow("Foo\n\n\"Bar1.\" Bar2.\n", "Foo\nn:foo=Foo\n\n\"Bar1.\"\ns=foo\n\nBar2.\ns=\n")]
	[DataRow("Foo\n\nBar1. Bar2.\n", "Foo\nn:foo=Foo\n\nBar1.\nt=foo\n\nBar2.\nt=\n")]
	[DataRow("\"Foo.\" Bar.\n", "\"Foo.\"\nn:f=foo;s=f\n\nBar.\ns=;t=f\n")]
	[DataRow("Foo. \"Bar.\"\n", "Foo.\nn:f=foo;t=f\n\n\"Bar.\"\nt=;s=f\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:foo=95\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:foo=95,46,5\n")]
	[DataRow("Foo\n", "<div class='upper'>Foo</div>\n\n")]
	public void Compiler_BuildHtml_GoodText(string rawText, string pulpText) {
		Compiler.BuildHtml(rawText, pulpText);
		Assert.IsTrue(Compiler.TryBuildHtml(rawText, pulpText, out string _));
	}

	[TestMethod]
	[DataRow("Foo\n", "foo\n\n")]
	[DataRow("Foo`\n", "Foo`\n\n")]
	[DataRow("\"Foo\n", "\"Foo\n\n")]
	[DataRow("Foo\n", "Foo\"\n\n")]
	[DataRow("Foo Bar.\n", "Foo\n\n\nBar.\n\n")]
	[DataRow("Foo Bar.\n", "Foo \n\n\nBar.\n\n")]
	[DataRow("Foo, Bar.\n", "Foo,\n\n\nBar.\n\n")]
	[DataRow("Foo, Bar.\n", "Foo,\n\n\nBar.\nd=joined\n")]
	[DataRow("Foo, Bar.\n", "Foo, \n\n\nBar.\n\n")]
	[DataRow("Foo- Bar.\n", "Foo-\n\n\nBar.\n\n")]
	[DataRow("Foo- Bar.\n", "Foo- \n\n\nBar.\n\n")]
	[DataRow("Foo— Bar.\n", "Foo— \n\n\nBar.\n\n")]
	[DataRow("Foo; Bar.\n", "Foo; \n\n\nBar.\n\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\n\n\nBar.\"\n\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\n\n\n\"Bar.\"\n\n")]
	[DataRow("\"Foo. Bar.\n\n\"Fizz. Buzz.\"\n", "\"Foo. Bar.\"\n\n\nFizz. \"Buzz.\"\n\n")]
	[DataRow("\"Foo. Bar. Foobar.\"\n", "\"Foo.\"\n\n\nBar.\n\n\n\"Foobar.\"\n\n")]
	[DataRow("Foo.\n\n\n\nBar.\n", "Foo.\n\n\n\n\n\nBar.\n\n")]
	[DataRow("Foo.\n\nBar.\n", "Foo.\n\n\n\n\n\nBar.\n\n")]
	[DataRow("Foo.\n\n\n\nBar.\n", "Foo.\n\n\n<e>Text</e>\n\n\nBar.\n\n")]
	[DataRow("Foo\x0005\n", "Foo\x0005\n\n")]
	[DataRow("Foo\r\n", "Foo\n\n")]
	[DataRow("Foo\n", "Foo\r\n\n")]
	[DataRow("Foo\n", "Foo\n")]
	[DataRow("F\ro\n", "Foo\n\n")]
	[DataRow("FooBar \n", "FooBar \n\n")]
	[DataRow(" FooBar\n", " FooBar\n\n")]
	[DataRow("Foo\tBar\n", " Foo\tBar\n\n")]
	[DataRow("Foo\nFizz\nBuzz\n", "Foo\n\n\nFizz\n\n\nBuzz\n\n")]
	[DataRow("Foo\n\nFizz\n\nBuzz\n", "Foo\n\nFizz\n\nBuzz\n\n")]
	[DataRow("Foo\n\nFizz\nBuzz\n", "Foo\n\n\nFizz\n\n\nBuzz\n\n")]
	[DataRow("Foo\n\nFizz\n\nBuzz\n", "Foo\n\n\nFizz\n\nBuzz\n\n")]
	[DataRow("Foo\n\nFizz\n\nBuzz\n", "Foo\n\n\nFizz\n\n\nFuzz\n\n")]
	[DataRow("Foo\n\nFizz\n\nBuzz\n", "FooFizz\n\n\nBuzz\n\n")]
	[DataRow("Foo\n\nFizz\n\nBuzz\n", "Foo Fizz\n\n\nBuzz\n\n")]
	[DataRow("Foo\n", "Foo\nq\n")]
	[DataRow("Foo\n", "Foo\nq=foo\n")]
	[DataRow("Foo\n", "Foo\nb:foo=\n")]
	[DataRow("Foo\n", "Foo\nb:foo=bar\n")]
	[DataRow("Foo\n", "Foo\nr:foo=\n")]
	[DataRow("Foo\n", "Foo\nr:foo=bar\n")]
	[DataRow("Foo\n", "Foo\nc=foo\n")]
	[DataRow("Foo\n", "Foo\nn:none=foo\n")]
	[DataRow("Foo\n", "Foo\nn:None=Foo\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=!!foo\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo!\n")]
	[DataRow("Foo\n", "Foo\nn=foo\n")]
	[DataRow("Foo\n", "Foo\ne:f=yay\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\ne:foo=boo=\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\ne:foo=foo-bar\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\ne:foo=foo bar\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\ne:foo=Foo\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\ne:foo=foo!\n")]
	[DataRow("Foo\n", "Foo\na:f=24\n")]
	[DataRow("\"Foo\"\n", "\"Foo\"\ns=f\n")]
	[DataRow("Foo\n", "Foo\nn:f=foo;s=f\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.”\n\n\n\"Bar.\"\n\n")]
	[DataRow("\"Foo. Bar.\"\n", "“Foo.”\n\n\n\"Bar.\"\n\n")]
	[DataRow("“Foo. Bar.”\n", "“Foo.”\n\n\n\"Bar\"\n\n")]
	[DataRow("Foo\n", "Foo\nt=f\n")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:f=foo;s=f;t=f\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:f=foo;s=f\n\n\"Bar.\"\nt=f\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:f=foo;t=f\n\n\"Bar.\"\ns=f\n")]
	[DataRow("Foo\n", "Foo\nc:foo=bar\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo,bar\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo,,,,,\n")]
	[DataRow("Foo\n", "Foo<e>lorem\n\n")]
	[DataRow("Foo\n", "Foo<e>lorem<e>\n\n")]
	[DataRow("Foo\n", "Foo<e>lorem<e>ipsum</e>lorem</e>\n\n")]
	[DataRow("Foo. Bar.\n", "<e>1</e>Foo.<e>2</e>\n\n\n\n\n\nBar.<e>4</e><e>5</e>\n\n")]
	[DataRow("Foo. Bar.\n", "<e>1</e>\n\n\nFoo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e>\n\n\n<e>5</e>\n\n\n\n\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z=foo:95\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:bar=95\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:foo=95,46\n")]
	[DataRow("Foo\n", "<p class='upper'>Foo</p>\n\n")]
	[DataRow("Foo\n", "<div class=\"upper\">Foo</div>\n\n")]
	[DataRow("Foo\n", "<div id='upper'>Foo</div>\n\n")]
	[DataRow("Foo\n", "<div class='up-per'>Foo</div>\n\n")]
	[DataRow("Foo\n", "<div>Foof</div>\n\n")]
	public void Compiler_BuildHtml_BadText(string rawText, string pulpText) {
		Assert.IsFalse(Compiler.TryBuildHtml(rawText, pulpText, out string _));
	}

	[TestMethod]
	[DataRow("Foo\n", "Foo\n\n", "Foo")]
	[DataRow("Foo\n", "Foo\n\n", "<div>Foo</div>")]
	[DataRow("Foo. Bar.\n", "Foo.\nd=margin\n\nBar.\nd=\n", "<div class='margin'>Foo.</div>")]
	[DataRow("Foo. Bar.\n", "Foo.\nd=margin\n\nBar.\nd=\n", "<div>Bar.</div>")]
	[DataRow("Foo; Bar. Fizz.\n", "Foo;\nd=joined\n\nBar.\nd=\n\nFizz.\n\n", "<div>Foo;</div>")]
	[DataRow("Foo; Bar. Fizz.\n", "Foo;\nd=joined\n\nBar.\nd=\n\nFizz.\n\n", "<div>Foo; Bar.</div>")]
	[DataRow("Foo; Bar. Fizz.\n", "Foo;\nd=joined\n\nBar.\nd=\n\nFizz.\n\n", "<div>Fizz.</div>")]
	[DataRow("*Foo*\n", "*Foo*\n\n", "<i>Foo</i>")]
	[DataRow("**Foo**\n", "**Foo**\n\n", "<span class='upper'>Foo</span>")]
	[DataRow("***Foo***\n", "***Foo***\n\n", "<i class='upper'>Foo</i>")]
	[DataRow("Foo\n", "<span class='upper'>Foo</span>\n\n", "<span class='upper'>Foo</span>")]
	[DataRow("Foo\n", "Foo<e>Bar</e>\n\n", "<span class='upper'>Editor's Note:</span> Bar")]
	[DataRow("*Foo*\n", "<e>1</e>*Foo*<e>2</e>\n\n", "<span class='upper'>Editor's Note:</span> 1")]
	[DataRow("*Foo*\n", "<e>1</e>*Foo*<e>2</e>\n\n", "<span class='upper'>Editor's Note:</span> 2")]
	[DataRow("*Foo*\n", "<e>1</e>*Foo*<e>2</e>\n\n", "<i>Foo</i>")]
	[DataRow("Foo\n", "Foo<e>*Bar*</e>\n\n", "*Bar*")]
	[DataRow("Foo. Bar.\n", "<e>0</e>\n\n\n<e>1</e>\n\n\nFoo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e>\n\n\n<e>5</e>\n\n\n<e>6</e>\n\n", "<span class='upper'>Editor's Note:</span> 0")]
	[DataRow("Foo. Bar.\n", "<e>0</e>\n\n\n<e>1</e>\n\n\nFoo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e>\n\n\n<e>5</e>\n\n\n<e>6</e>\n\n", "<span class='upper'>Editor's Note:</span> 1")]
	[DataRow("Foo. Bar.\n", "<e>0</e>\n\n\n<e>1</e>\n\n\nFoo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e>\n\n\n<e>5</e>\n\n\n<e>6</e>\n\n", "<span class='upper'>Editor's Note:</span> 5")]
	[DataRow("Foo. Bar.\n", "<e>0</e>\n\n\n<e>1</e>\n\n\nFoo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e>\n\n\n<e>5</e>\n\n\n<e>6</e>\n\n", "<span class='upper'>Editor's Note:</span> 6")]
	[DataRow("# Foo\n", "# Foo\n\n", "<h1 class='upper'>Foo</h1>")]
	[DataRow("## Foo\n", "## Foo\n\n", "<h1 class='upper'>Foo</h1>")]
	[DataRow("### Foo\n", "### Foo\n\n", "<h2 class='upper'>Foo</h2>")]
	[DataRow("#### Foo\n", "#### Foo\n\n", "<h3 class='upper'>Foo</h3>")]
	[DataRow("## Foo *Bar*\n", "## Foo *Bar*\n\n", "<h1 class='upper'>Foo <i>Bar</i></h1>")]
	[DataRow("Foo\n", "Foo<e>Book: <book>Some Book</book></e>\n\n", "Book: <i><a href='")]
	[DataRow("Foo\n", "Foo<e>Book: <book>Some Book</book></e>\n\n", ">Some Book</a>")]
	[DataRow("Foo\n", "Foo<e>Story: <book>\"Some Story\"</book></e>\n\n", "Story: <a href='")]
	[DataRow("Foo\n", "Foo<e>Story: <book>\"Some Story\"</book></e>\n\n", ">\"Some Story\"</a>")]
	[DataRow("Foo\n", "Foo<e>Book: <book>Some Book|the book</book></e>\n\n", "Book: <a href='")]
	[DataRow("Foo\n", "Foo<e>Book: <book>Some Book|the book</book></e>\n\n", ">the book</a>")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r\n", "c-r.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;c=r;s=r\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;c=r;s=r\n\n\"Bar.\"\ns=\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;c=r;s=r\n\n\"Bar.\"\ns=\n", "c-r.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;c=r;s=r\n\n\"Bar.\"\ns=none\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;c=r;s=r\n\n\"Bar.\"\ns=none\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;e:r=u\n", "c-r-eu.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;e:r=neutral\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r\n", "'p-1/2'")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=!r\n", "'f p-1/2'")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=,r\n", "'p-2/3'")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=,!r\n", "'f p-2/3'")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;x:r=foo\n", "c-r-xfoo.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;x:r=\n", "c-r.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=foo\n\nBar.\nx:r=\n", "c-r.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=foo\n\nBar.\nx:r=\n", "c-r-xfoo.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=foo\n\nBar.\nx:r=bar\n", "c-r-xfoo.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=foo\n\nBar.\nx:r=bar\n", "c-r-xbar.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=foo\n\nBar.\nx:r=foo,bar\n", "c-r-xfoo.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=foo\n\nBar.\nx:r=foo,bar\n", "c-r-xbar-xfoo.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;a:r=foo\n", "c-r-afoo.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;a:r=foo\n\nBar.\na:r=\n", "c-r-afoo.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;a:r=foo\n\nBar.\na:r=\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;t=r\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;t=r\n", "c-r.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;t=r\n\nBar.\nt=none\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;t=r;e:r=t\n", "c-r-et.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;t=r;e:r=t\n", "c-r-et.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;e:r=m;t=r\n", "c-r-em.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;c=r;e:r=g;s=r\n", "c-r-eg-s.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;e:r=g;s=r\n", "c-r-eg-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\n\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\n\n", "c-r-s2.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;e:r=g;s=r\n\n\"Bar.\"\n\n", "c-r-eg-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;e:r=g;s=r\n\n\"Bar.\"\n\n", "c-r-eg-s2.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\ne:r=g\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\ne:r=g\n", "c-r-eg-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;e:r=g\n\n\"Bar.\"\ne:r=\n", "c-r-eg-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;e:r=g\n\n\"Bar.\"\ne:r=\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\nx:r=foo\n", "c-r-xfoo-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\na:r=foo\n", "c-r-afoo-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;x:r=foo\n\n\"Bar.\"\n\n", "c-r-xfoo-s2.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;a:r=foo\n\n\"Bar.\"\n\n", "c-r-afoo-s2.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;x:r=foo;e:r=g\n\n\"Bar.\"\n\n", "c-r-xfoo-eg-s2.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;a:r=foo;e:r=g\n\n\"Bar.\"\n\n", "c-r-afoo-eg-s2.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;e:r=g;s=r;a:r=foo;x:r=bar\n", "c-r-afoo-xbar-eg-s.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;e:r=g;s=r;a:r=foo;x:r=fizz,buzz\n", "c-r-afoo-xbuzz-xfizz-eg-s.webp")]
	[DataRow("\"Foo.\"\n\n\"Bar.\"\n\n\"Fizz.\"\n", "\"Foo.\"\nn:r=R;n:j=J;s=r;c=r,j\n\n\"Bar.\"\ns=j\n\n\"Fizz.\"\ns=r\n", "c-r-s2.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=bar\n\nBar.\nx:r=\n", "c-r-xbar.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=bar\n\nBar.\nx:r=\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;n:f=F;c=r,f\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;n:f=F;c=r,f\n", "c-f.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;e:r=g;x:r=bar\n\nBar.\nr=p;c=r\n", "c-r.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;e:r=g;a:r=foo;x:r=bar\n\nBar.\nr=p;c=r\n", "c-r-afoo.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;e:r=g;s=r;a:r=foo;x:r=bar\n\n\"Bar.\"\nr=p;c=r\n", "c-r-afoo.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;e:r=g;a:r=foo;x:r=bar\n\n\"Bar.\"\nr=p;s=r\n", "c-r-afoo-s.webp")]
	[DataRow("Foo\n", "Foo\no=myobj\n", "o-myobj.webp")]
	[DataRow("Foo\n", "Foo\no=myobj\n", "class='c'")]
	[DataRow("Foo\n", "Foo\nb=p\n", "'p'")]
	[DataRow("Foo\n", "Foo\nr=p\n", "'p'")]
	[DataRow("Foo\n", "Foo\nb=p;m:p=foo,bar\n", "'p-mod-bar-foo'")]
	[DataRow("Foo. Bar.\n", "Foo.\nb=p;m:p=foo\n\nBar.\nm:p=bar\n", "'p-mod-foo'")]
	[DataRow("Foo. Bar.\n", "Foo.\nb=p;m:p=foo\n\nBar.\nm:p=bar\n", "'p-mod-bar'")]
	[DataRow("Foo. Bar.\n", "Foo.\nb=p;m:p=foo\n\nBar.\nr=p\n", "'p-mod-foo'")]
	[DataRow("Foo. Bar.\n", "Foo.\nb=p;m:p=foo\n\nBar.\nr=p\n", "'p'")]
	[DataRow("“Foo” said Foo. “Bar.”\n", "“Foo” said Foo. “Bar.”\nn:f=Foo;s=f\n", "<span class='d'>“Foo”</span> said Foo. <span class='d'>“Bar.”</span>")]
	public void Compiler_BuildHtml_ContainsHtml(string rawText, string pulpText, string htmlSnippet) {
		string html = Compiler.BuildHtml(rawText, pulpText);
		Assert.Contains(htmlSnippet, html);
	}
}