namespace Pulp.Pulpifier.Tests;

[TestClass]
public class CompilerTests {
	[TestMethod]
	[DataRow("Foo\n", "Foo\n\n")]
	[DataRow("Foo Bar\n", "Foo Bar\n\n")]
	[DataRow("Foo Bar\n", "Foo&nbsp;Bar\n\n")]
	[DataRow("Foo. Bar.\n", "Foo.\n\n\nBar.\n\n")]
	[DataRow("Foo. Bar.\n", "Foo. \nm=nospace\n\nBar.\nm=\n")]
	[DataRow("Foo. Bar.\n", "Foo.\nm=nospace;m=joined\n\n Bar.\nm=\n")]
	[DataRow("Foo! Bar.\n", "Foo!\n\n\nBar.\n\n")]
	[DataRow("Foo? Bar.\n", "Foo?\n\n\nBar.\n\n")]
	[DataRow("“Foo! Bar.”\n", "“Foo!”\n\n\n“Bar.”\n\n")]
	[DataRow("“Foo? Bar.”\n", "“Foo?”\n\n\n“Bar.”\n\n")]
	[DataRow("Foo— Bar.\n", "Foo—\n\n\nBar.\n\n")]
	[DataRow("Foo; Bar.\n", "Foo;\n\n\nBar.\n\n")]
	[DataRow("*Foo*. Bar.\n", "*Foo*.\n\n\nBar.\n\n")]
	[DataRow("(Foo.) Bar.\n", "(Foo.)\n\n\nBar.\n\n")]
	[DataRow("\"'Foo.'\" Bar.\n", "\"'Foo.'\"\n\n\nBar.\n\n")]
	[DataRow("Foo, “Bar.”\n", "Foo,\n\n\n“Bar.”\n\n")]
	[DataRow("Foo, \"Bar.\"\n", "Foo,\n\n\n\"Bar.\"\n\n")]
	[DataRow("Foo, Bar.\n", "Foo,\nm=joined\n\nBar.\n\n")]
	[DataRow("Foo, Bar.\n", "Foo,\nm=joined\n\nBar.\nm=\n")]
	[DataRow("Foo, Bar.\n", "Foo,\nm=allowbreak\n\nBar.\nm=\n")]
	[DataRow("Foo Bar.\n", "Foo\nm=allowbreak\n\nBar.\nm=\n")]
	[DataRow("Foo, Bar.\n", "Foo,\nm=break\n\nBar.\nm=\n")]
	[DataRow("Foo. Bar\n", "Foo. <e>lorem</e>Bar\n\n")]
	[DataRow("Foo Bar\n", "<e>lorem</e>Foo Bar<e>ipsum</e>\n\n")]
	[DataRow("Foo Bar\n", "<e>lorem</e>Foo <e>mid</e>Bar<e>ipsum</e>\n\n")]
	[DataRow("Foo. Bar.\n", "<e>1</e>Foo.<e>2</e> <e>3</e>Bar.<e>4</e><e>5</e>\n\n")]
	[DataRow("Foo. Bar.\n", "<e>1</e>Foo.<e>2</e>\n\n\n<e>3</e>Bar.<e>4</e><e>5</e>\n\n")]
	[DataRow("Foo. Bar.\n", "<e>1</e>Foo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e><e>5</e>\n\n")]
	[DataRow("Foo. Bar.\n", "<e>1</e>\n\n\nFoo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e>\n\n\n<e>5</e>\n\n")]
	[DataRow("Foo\n\nFizz\n\nBuzz\n", "Foo\n\n\nFizz\n\n\nBuzz\n\n")]
	[DataRow("\"Foo\"\n", "\"Foo\"\n\n")]
	[DataRow("\"Foo\" foo Foo. \"Foo.\"\n", "\"Foo\" foo Foo. \"Foo.\"\n\n")]
	[DataRow("\"Foo\" foo Foo. \"Foo.\"\n", "\"Foo\" foo Foo.\n\n\n\"Foo.\"\n\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\n\n\n\"Bar.\"\n\n")]
	[DataRow("“Foo. Bar.”\n", "“Foo.”\n\n\n“Bar.”\n\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\n\n\n<e>edit</e>\n\n\n\"Bar.\"\n\n")]
	[DataRow("“Foo. Bar.”\n", "“Foo.”\n\n\n<e>edit</e>\n\n\n“Bar.”\n\n")]
	[DataRow("\"Foo. Bar. Foobar.\"\n", "\"Foo.\"\n\n\n\"Bar.\"\n\n\n\"Foobar.\"\n\n")]
	[DataRow("\"Foo. Bar.\n\n\"Fizz. Buzz.\"\n", "\"Foo. Bar.\"\n\n\n\"Fizz. Buzz.\"\n\n")]
	[DataRow("\"Foo. Bar.\n\n\"Fizz. Buzz.\"\n", "\"Foo.\"\n\n\n\"Bar.\"\n\n\n\"Fizz.\"\n\n\n\"Buzz.\"\n\n")]
	[DataRow("Foo.\n\nBar.\n", "Foo.\n\n\n<e>Text</e>\n\n\nBar.\n\n")]
	[DataRow("Foo. Fizz\n\nBuzz\n", "Foo.\n\n\nFizz\n\n\nBuzz\n\n")]
	[DataRow("Foo. Fizz\n\nBuzz\n", "Foo.<e>lorem</e>\n\n\nFizz<e>ipsum</e>\n\n\nBuzz\n\n")]
	[DataRow("Foo\n", "Foo\nb=back\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;n:bar=Bar;c=foo,bar\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;n:bar=Bar;c=foo,,bar\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;n:bar=Bar;c=,foo,,bar,\n")]
	[DataRow("Foo\n\nBar\n", "Foo\n\n\nBar\n\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\nn:foo=FOO\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo;c=foo\n\nBar\nc=\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\nc=foo\n")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:f=foo;s=f\n")]
	[DataRow("Foo\n", "Foo\nn:f=foo;t=f\n")]
	[DataRow("Foo\n\n\"Bar\"\n", "Foo\nn:foo=Foo\n\n\"Bar\"\ns=foo\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\nt=foo\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\ne:foo=boo\n")]
	[DataRow("Foo\n\n\"Bar\"\n", "Foo\nn:foo=Foo\n\n\"Bar\"\ns=foo;c=foo;e:foo=boo\n")]
	[DataRow("Foo\n\n“Bar”\n", "Foo\nn:foo=Foo\n\n“Bar”\ns=foo;c=foo;e:foo=boo\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\nt=foo;c=foo;e:foo=boo\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\na:foo=24\n")]
	[DataRow("Foo\n\n\"Bar\"\n", "Foo\nn:foo=Foo\n\n\"Bar\"\ns=foo;c=foo;a:foo=old\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\nt=foo;c=foo;a:foo=old\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\nx:foo=tie\n")]
	[DataRow("Foo\n", "Foo\nn:f=F;c=f;e:f=hip;a:f=99\n")]
	[DataRow("Foo\n\n\"Bar1.\" Bar2.\n", "Foo\nn:foo=Foo\n\n\"Bar1.\"\ns=foo\n\nBar2.\ns=\n")]
	[DataRow("Foo\n\nBar1. Bar2.\n", "Foo\nn:foo=Foo\n\nBar1.\nt=foo\n\nBar2.\nt=\n")]
	[DataRow("\"Foo.\" Bar.\n", "\"Foo.\"\nn:f=foo;s=f\n\nBar.\ns=;t=f\n")]
	[DataRow("Foo. \"Bar.\"\n", "Foo.\nn:f=foo;t=f\n\n\"Bar.\"\nt=;s=f\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:foo=95\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:foo=95,46\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:foo=95,46,5\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:foo=95,46,5,105\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:foo=95,,,105\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:foo=,,-1,\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:foo=,,,\n")]
	[DataRow("Foo\n", "Foo\nv=100,150,40\n")]
	[DataRow("Foo\n", "Foo\nv=,150,\n")]
	[DataRow("Foo\n", "Foo\nv=,,\n")]
	[DataRow("Foo\n", "<div class='upper'>Foo</div>\n\n")]
	[DataRow("Foo\n", "Foo\nb=foo;f:b:foo=blur(5px)\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo;f:c:foo=blur(5px)\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo;i:foo=2\n")]
	[DataRow("“Foo.”\n", "“Foo.”\nn:foo=Foo;s=foo;i:foo=2\n")]
	[DataRow("“Foo.”\n", "“Foo.”\nn:foo=Foo;s=foo;i=2\n")]
	[DataRow("“Foo.”\n", "“Foo.”\nn:foo=Foo;t=foo;i=2\n")]
	[DataRow("“‘Foo. Bar.’”\n", "“‘Foo.’”\n\n\n“‘Bar.’”\n\n")]
	[DataRow("“‘Foo. Bar.’ Fizz.”\n", "“‘Foo.’”\n\n\n“‘Bar.’”\n\n\n“Fizz.”\n\n")]
	[DataRow("“‘Foo. Bar.’ Fizz.”\n", "“‘Foo.’”\n\n\n“‘Bar.’ Fizz.”\n\n")]
	[DataRow("“‘Foo. Bar.’ Fizz.”\n", "“‘Foo. Bar.’”\n\n\n“Fizz.”\n\n")]
	[DataRow("“‘Foo. Fizz. Buzz. Bar.’”\n", "“‘Foo.’”\n\n\n“‘Fizz. Buzz.’”\n\n\n“‘Bar.’”\n\n")]
	[DataRow("“‘Foo. Fizz. Buzz. Bar.’”\n", "“‘Foo.’”\n\n\n“‘Fizz.’”\n\n\n“‘Buzz.’”\n\n\n“‘Bar.’”\n\n")]
	[DataRow("“‘Foo. Fizz,’ says the guy. So I says to the guy. I says: ‘Buzz. Bar.’”\n", "“‘Foo.’”\n\n\n“‘Fizz,’ says the guy. So I says to the guy. I says: ‘Buzz.’”\n\n\n“‘Bar.’”\n\n")]
	[DataRow("Ăß©\n", "Ăß©\n\n")]
	[DataRow("Foo\n", "Foo<e><book>Invisible Man</book></e>\n\n")]
	[DataRow("Foo\n", "Foo<e><book>\"Invisible Man\"</book></e>\n\n")]
	[DataRow("Foo\n", "Foo<e><book>The Invisible Man</book></e>\n\n")]
	[DataRow("## Foo\n", "## Foo\n\n")]
	[DataRow("## Foo<br>Bar\n", "## Foo<br>Bar\n\n")]
	[DataRow("## Foo. Bar\n", "## Foo<br>Bar\n\n")]
	[DataRow("## I. “Quote”\n", "## I<br>“Quote”\n\n")]
	[DataRow("Foo. Bar.\n", "Foo.<f>Footnote.</f> Bar.\n\n")]
	[DataRow("Foo. Bar.\n", "Foo.<f>Footnote.</f>\n\n\nBar.\n\n")]
	[DataRow("Foo. Bar.\n", "Foo.<f>Footnote.</f>\n\n\n<f>Footnote 2.</f>Bar.\n\n")]
	[DataRow("Foo. Bar.\n", "Foo. Bar.<e>E</e><f>F</f>\n\n")]
	[DataRow("Foo. Bar.\n", "Foo. Bar.<f>F</f><e>E</e>\n\n")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\n\n\n“‘Bar.’”\n\n\n“‘“Fizz.”’”\n\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\n\n\n“Foo.”\n\n")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2;b=b2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2;b=b2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ns=;\n\n“Foo.”\ng=;g=\n")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;g=b3;s=;b=b2\n\n“‘“Fizz.”’”\ns=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;s=s2;\n\n“Foo.”\ng=\n")]
	[DataRow("Foo. Foo. “Bar. Bar.” Foo.\n", "Foo.\n\n\nFoo.\n\n\n“Bar.”\nn:b=Bar;s=b\n\n“Bar.”\n\n\nFoo.\ns=\n")]
	[DataRow("Foo. Foo. “Bar. Bar.” Foo.\n", "Foo.\nb=b1\n\nFoo.\ng=b2\n\n“Bar.”\nn:b=Bar;s=b\n\n“Bar.”\n\n\nFoo.\ns=;g=\n")]
	[DataRow("Foo. Foo. “Bar. Bar.” Foo.\n", "Foo.\nb=b1\n\nFoo.\n\n\n“Bar.”\nn:b=Bar;g=b2;s=b\n\n“Bar.”\n\n\nFoo.\ns=;g=\n")]
	[DataRow("Foo. Foo. “Bar. Bar.” Foo.\n", "Foo.\nb=b1\n\nFoo.\n\n\n“Bar.”\nn:b=Bar;s=b\n\n“Bar.”\ng=b2\n\nFoo.\ng=;s=\n")]
	[DataRow("Foo\n", "Foo\nb=foo;f=lightning\n")]
	[DataRow("Foo. Bar. Fizz.\n", "Foo.\nb=foo\n\nBar.\n\n\nFizz.\nf=fade\n")]
	public void Compiler_BuildHtml_GoodText(string rawText, string pulpText) {
		Compiler.BuildHtml(rawText, pulpText);
		Assert.IsTrue(Compiler.TryBuildHtml(rawText, pulpText, out string _));
	}

	[TestMethod]
	[DataRow("Foo\n", "foo\n\n")]
	[DataRow("Foo`\n", "Foo`\n\n")]
	[DataRow("\"Foo\n", "\"Foo\n\n")]
	[DataRow("Foo\n", "Foo\"\n\n")]
	[DataRow("Foo. Bar.\n", "Foo.\nm=nospace\n\nBar.\nm=\n")]
	[DataRow("Foo. Bar.\n", "Foo. \n\n\nBar.\nm=nospace\n")]
	[DataRow("Foo. Bar.\n", "Foo. \n\n\nBar.\n\n")]
	[DataRow("Foo Bar.\n", "Foo\n\n\nBar.\n\n")]
	[DataRow("Foo Bar.\n", "Foo \n\n\nBar.\n\n")]
	[DataRow("Foo, Bar.\n", "Foo,\n\n\nBar.\n\n")]
	[DataRow("Foo, Bar.\n", "Foo,\n\n\nBar.\nm=joined\n")]
	[DataRow("Foo, Bar.\n", "Foo,\n\n\nBar.\nm=allowbreak\n")]
	[DataRow("Foo, Bar.\n", "Foo, \n\n\nBar.\n\n")]
	[DataRow("Foo- Bar.\n", "Foo-\n\n\nBar.\n\n")]
	[DataRow("Foo- Bar.\n", "Foo- \n\n\nBar.\n\n")]
	[DataRow("Foo— Bar.\n", "Foo— \n\n\nBar.\n\n")]
	[DataRow("Foo; Bar.\n", "Foo; \n\n\nBar.\n\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\n\n\nBar.\"\n\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\n\n\n\"Bar.\"\n\n")]
	[DataRow("\"Foo. Bar.\n\n\"Fizz. Buzz.\"\n", "\"Foo. Bar.\"\n\n\nFizz. \"Buzz.\"\n\n")]
	[DataRow("\"Foo. Bar. Foobar.\"\n", "\"Foo.\"\n\n\nBar.\n\n\n\"Foobar.\"\n\n")]
	[DataRow("Foo.\n\n\n\nBar.\n", "Foo.\n\n\n\n\n\nBar.\n\n")]
	[DataRow("Foo.\n\nBar.\n", "Foo.\n\n\n\n\n\nBar.\n\n")]
	[DataRow("Foo.\n\n\n\nBar.\n", "Foo.\n\n\n<e>Text</e>\n\n\nBar.\n\n")]
	[DataRow("Foo\x0005\n", "Foo\x0005\n\n")]
	[DataRow("Foo\r\n", "Foo\n\n")]
	[DataRow("Foo\n", "Foo\r\n\n")]
	[DataRow("Foo\n", "Foo\n")]
	[DataRow("F\ro\n", "Foo\n\n")]
	[DataRow("FooBar \n", "FooBar \n\n")]
	[DataRow(" FooBar\n", " FooBar\n\n")]
	[DataRow("Foo\tBar\n", " Foo\tBar\n\n")]
	[DataRow("Foo\nFizz\nBuzz\n", "Foo\n\n\nFizz\n\n\nBuzz\n\n")]
	[DataRow("Foo\n\nFizz\n\nBuzz\n", "Foo\n\nFizz\n\nBuzz\n\n")]
	[DataRow("Foo\n\nFizz\nBuzz\n", "Foo\n\n\nFizz\n\n\nBuzz\n\n")]
	[DataRow("Foo\n\nFizz\n\nBuzz\n", "Foo\n\n\nFizz\n\nBuzz\n\n")]
	[DataRow("Foo\n\nFizz\n\nBuzz\n", "Foo\n\n\nFizz\n\n\nFuzz\n\n")]
	[DataRow("Foo\n\nFizz\n\nBuzz\n", "FooFizz\n\n\nBuzz\n\n")]
	[DataRow("Foo\n\nFizz\n\nBuzz\n", "Foo Fizz\n\n\nBuzz\n\n")]
	[DataRow("Foo\n", "Foo\nq\n")]
	[DataRow("Foo\n", "Foo\nq=foo\n")]
	[DataRow("Foo\n", "Foo\nb:foo=\n")]
	[DataRow("Foo\n", "Foo\nb:foo=bar\n")]
	[DataRow("Foo\n", "Foo\nr:foo=\n")]
	[DataRow("Foo\n", "Foo\nr:foo=bar\n")]
	[DataRow("Foo\n", "Foo\nc=foo\n")]
	[DataRow("Foo\n", "Foo\nn:none=foo\n")]
	[DataRow("Foo\n", "Foo\nn:None=Foo\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=!foo\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=!!foo\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo!\n")]
	[DataRow("Foo\n", "Foo\nn=foo\n")]
	[DataRow("Foo\n", "Foo\ne:f=yay\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\ne:foo=boo=\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\ne:foo=foo-bar\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\ne:foo=foo bar\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\ne:foo=Foo\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nn:foo=Foo\n\nBar\ne:foo=foo!\n")]
	[DataRow("Foo\n", "Foo\na:f=24\n")]
	[DataRow("\"Foo\"\n", "\"Foo\"\ns=f\n")]
	[DataRow("Foo\n", "Foo\nn:f=foo;s=f\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.”\n\n\n\"Bar.\"\n\n")]
	[DataRow("\"Foo. Bar.\"\n", "“Foo.”\n\n\n\"Bar.\"\n\n")]
	[DataRow("“Foo. Bar.”\n", "“Foo.”\n\n\n\"Bar\"\n\n")]
	[DataRow("Foo\n", "Foo\nt=f\n")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:f=foo;s=f;t=f\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:f=foo;s=f\n\n\"Bar.\"\nt=f\n")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:f=foo;t=f\n\n\"Bar.\"\ns=f\n")]
	[DataRow("Foo\n", "Foo\nc:foo=bar\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo,bar\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo,,,,,\n")]
	[DataRow("Foo\n", "Foo<e>lorem\n\n")]
	[DataRow("Foo\n", "Foo<e>lorem<e>\n\n")]
	[DataRow("Foo\n", "Foo<e>lorem<e>ipsum</e>lorem</e>\n\n")]
	[DataRow("Foo. Bar.\n", "<e>1</e>Foo.<e>2</e>\n\n\n\n\n\nBar.<e>4</e><e>5</e>\n\n")]
	[DataRow("Foo. Bar.\n", "<e>1</e>\n\n\nFoo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e>\n\n\n<e>5</e>\n\n\n\n\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z=foo:95\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:bar=95\n")]
	[DataRow("Foo\n", "<p class='upper'>Foo</p>\n\n")]
	[DataRow("Foo\n", "<div class=\"upper\">Foo</div>\n\n")]
	[DataRow("Foo\n", "<div id='upper'>Foo</div>\n\n")]
	[DataRow("Foo\n", "<div class='up-per'>Foo</div>\n\n")]
	[DataRow("Foo\n", "<div>Foof</div>\n\n")]
	[DataRow("Foo\n", "Foo\nb=foo;f:b:bar=blur(5px)\n")]
	[DataRow("Foo\n", "Foo\nb=foo;f:c:foo=blur(5px)\n")]
	[DataRow("Foo\n\nBar\n", "Foo\nm=joined\n\nBar\n\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;z:foo=,,,,\n")]
	[DataRow("Foo\n", "Foo\nv=,,,\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;i:foo=2\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo;i=2\n")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;i=2\n")]
	[DataRow("“‘Foo. Bar.’”\n", "“‘Foo.”\n\n\n“Bar.’”\n\n")]
	[DataRow("“‘Foo. Bar.’”\n", "“‘Foo.”\n\n\n“‘Bar.’”\n\n")]
	[DataRow("“‘Foo. Bar.’”\n", "“‘Foo.’”\n\n\n“Bar.’”\n\n")]
	[DataRow("♔\n", "♔\n\n")]
	[DataRow("Foo. ₿ar.\n", "Foo.\n\n\n₿ar.\n\n")]
	[DataRow("Foo\n", "Foo<e><book>Visible Man</book></e>\n\n")]
	[DataRow("Foo\n", "Foo<e><book>\"Visible Man\"</book></e>\n\n")]
	[DataRow("Foo\n", "Foo<e><book>The Visible Man</book></e>\n\n")]
	[DataRow("## Foo<br>Bar<br>Bar\n", "## Foo<br>Bar<br>Bar\n\n")]
	[DataRow("Foo. Bar.\n", "Foo. <f>Bar.</f>\n\n")]
	[DataRow("Foo. Bar.\n", "Foo. Bar.<e>Lorem<f>Ipsum</f></e>\n")]
	[DataRow("Foo. Bar.\n", "Foo. Bar.<e>Lorem<f>Ipsum</e></f>\n")]
	[DataRow("Foo. Bar.\n", "Foo. Bar.<e><e>E</e></e>\n")]
	[DataRow("Foo. Bar.\n", "Foo. Bar.<f><f>F</f></f>\n")]
	[DataRow("Foo. Bar.\n", "Foo.<f>F1</f> Bar.<f>F2</f>\n")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2;b=b2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\n\n")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2;b=b2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\n\n\n“Foo.”\ng=;g=\n")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1;g=b2;s=s2;b=b2\n\n“‘Bar.’”\ns=s2;b=b2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=;s=s2;b=b2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2,;s=s2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n")]
	[DataRow("Foo\n", "Foo\nb=back,\n")]
	[DataRow("Foo\n", "Foo\nb=foo;f=bad\n")]
	[DataRow("Foo\n", "Foo\nb=foo;f=blur(3px)\n")]
	public void Compiler_BuildHtml_BadText(string rawText, string pulpText) {
		Assert.IsFalse(Compiler.TryBuildHtml(rawText, pulpText, out string _));
	}

	[TestMethod]
	[DataRow("Foo\n", "Foo\n\n", "Foo")]
	[DataRow("Foo\n", "Foo\n\n", "<div>Foo</div>")]
	[DataRow("Foo. Bar.\n", "Foo.\nm=margin\n\nBar.\nm=\n", "<div class='margin'>Foo.</div>")]
	[DataRow("Foo. Bar.\n", "Foo.\nm=margin\n\nBar.\nm=\n", "<div>Bar.</div>")]
	[DataRow("Foo; Bar. Fizz.\n", "Foo;\nm=joined\n\nBar.\nm=\n\nFizz.\n\n", "<div>Foo;</div>")]
	[DataRow("Foo; Bar. Fizz.\n", "Foo;\nm=joined\n\nBar.\nm=\n\nFizz.\n\n", "<div>Foo; Bar.</div>")]
	[DataRow("Foo; Bar. Fizz.\n", "Foo;\nm=joined\n\nBar.\nm=\n\nFizz.\n\n", "<div>Fizz.</div>")]
	[DataRow("Foo-Bar.\n", "Foo-\nm=joined;m=nospace\n\nBar.\nm=\n", "<div>Foo-</div>")]
	[DataRow("Foo-Bar.\n", "Foo-\nm=joined;m=nospace\n\nBar.\nm=\n", "<div>Foo-Bar.</div>")]
	[DataRow("Foo-Bar. Fizz.\n", "Foo-\nm=joined;m=nospace;m=margin\n\nBar.\nm=;m=margin\n\nFizz.\nm=\n", "<div class='margin'>Foo-Bar.</div>")]
	[DataRow("Foo-Bar. Fizz.\n", "Foo-\nm=joined;m=nospace;m=margin\n\nBar.\nm=;m=margin\n\nFizz.\nm=\n", "<div>Fizz.</div>")]
	[DataRow("Foo Bar.\n", "Foo\nm=allowbreak\n\nBar.\nm=\n", "<div>Foo</div>")]
	[DataRow("Foo Bar.\n", "Foo\nm=allowbreak\n\nBar.\nm=\n", "<div>Bar.</div>")]
	[DataRow("*Foo*\n", "*Foo*\n\n", "<i>Foo</i>")]
	[DataRow("**Foo**\n", "**Foo**\n\n", "<span class='upper'>Foo</span>")]
	[DataRow("***Foo***\n", "***Foo***\n\n", "<i class='upper'>Foo</i>")]
	[DataRow("Foo\n", "<span class='upper'>Foo</span>\n\n", "<span class='upper'>Foo</span>")]
	[DataRow("Foo\n", "Foo<e>Bar</e>\n\n", "<span class='upper'>Editor's Note:</span> Bar")]
	[DataRow("*Foo*\n", "<e>1</e>*Foo*<e>2</e>\n\n", "<span class='upper'>Editor's Note:</span> 1")]
	[DataRow("*Foo*\n", "<e>1</e>*Foo*<e>2</e>\n\n", "<span class='upper'>Editor's Note:</span> 2")]
	[DataRow("Foo\n", "<span>Foo</span>\n\n", "<span>Foo</span>")]
	[DataRow("*Foo*\n", "<e>1</e>*Foo*<e>2</e>\n\n", "<i>Foo</i>")]
	[DataRow("Foo\n", "Foo<e>*Bar*</e>\n\n", "*Bar*")]
	[DataRow("Foo. Bar.\n", "<e>0</e>\n\n\n<e>1</e>\n\n\nFoo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e>\n\n\n<e>5</e>\n\n\n<e>6</e>\n\n", "<span class='upper'>Editor's Note:</span> 0")]
	[DataRow("Foo. Bar.\n", "<e>0</e>\n\n\n<e>1</e>\n\n\nFoo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e>\n\n\n<e>5</e>\n\n\n<e>6</e>\n\n", "<span class='upper'>Editor's Note:</span> 1")]
	[DataRow("Foo. Bar.\n", "<e>0</e>\n\n\n<e>1</e>\n\n\nFoo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e>\n\n\n<e>5</e>\n\n\n<e>6</e>\n\n", "<span class='upper'>Editor's Note:</span> 5")]
	[DataRow("Foo. Bar.\n", "<e>0</e>\n\n\n<e>1</e>\n\n\nFoo.<e>2</e>\n\n\n<e>3</e>\n\n\nBar.<e>4</e>\n\n\n<e>5</e>\n\n\n<e>6</e>\n\n", "<span class='upper'>Editor's Note:</span> 6")]
	[DataRow("# Foo\n", "# Foo\n\n", "<h1 class='heading'>Foo</h1>")]
	[DataRow("## Foo\n", "## Foo\n\n", "<h1 class='heading'>Foo</h1>")]
	[DataRow("### Foo\n", "### Foo\n\n", "<h2 class='heading'>Foo</h2>")]
	[DataRow("#### Foo\n", "#### Foo\n\n", "<h3 class='heading'>Foo</h3>")]
	[DataRow("## Foo *Bar*\n", "## Foo *Bar*\n\n", "<h1 class='heading'>Foo <i>Bar</i></h1>")]
	[DataRow("## Foo<br>Bar\n", "## Foo<br>Bar\n\n", "<h2 class='heading'>Foo<span>Bar</span></h2>")]
	[DataRow("### Foo<br>Bar\n", "### Foo<br>Bar\n\n", "<h3 class='heading'>Foo<span>Bar</span></h3>")]
	[DataRow("## Foo. Bar\n", "## Foo<br>Bar\n\n", "<h2 class='heading'>Foo<span>Bar</span></h2>")]
	[DataRow("### Foo. Bar\n", "### Foo<br>Bar\n\n", "<h3 class='heading'>Foo<span>Bar</span></h3>")]
	[DataRow("## Foo. Bar\n", "## Foo. Bar\n\n", "<h1 class='heading'>Foo. Bar</h1>")]
	[DataRow("### Foo. Bar\n", "### Foo. Bar\n\n", "<h2 class='heading'>Foo. Bar</h2>")]
	[DataRow("Foo\n", "Foo<e>Book: <book>Wisconsin Death Trip</book></e>\n\n", "Book: <i><a href='")]
	[DataRow("Foo\n", "Foo<e>Book: <book>Wisconsin Death Trip</book></e>\n\n", ">Wisconsin Death Trip</a>")]
	[DataRow("Foo\n", "Foo<e>Story: <book>\"Wisconsin Death Trip\"</book></e>\n\n", "Story: <a href='")]
	[DataRow("Foo\n", "Foo<e>Story: <book>\"Wisconsin Death Trip\"</book></e>\n\n", ">\"Wisconsin Death Trip\"</a>")]
	[DataRow("Foo\n", "Foo<e>Book: <book>Wisconsin Death Trip|the book</book></e>\n\n", "Book: <a href='")]
	[DataRow("Foo\n", "Foo<e>Book: <book>Wisconsin Death Trip|the book</book></e>\n\n", ">the book</a>")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r\n", "c-r.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;c=r;s=r\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;c=r;s=r\n\n\"Bar.\"\ns=\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;c=r;s=r\n\n\"Bar.\"\ns=;e:r=h\n", "c-r-eh.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;c=r;s=r\n\n\"Bar.\"\ns=none\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;c=r;s=r\n\n\"Bar.\"\ns=none;e:r=h\n", "c-r-eh.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;e:r=u\n", "c-r-eu.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;e:r=neutral\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r\n", "'p-1/2'")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=,r\n", "'p-2/3'")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;x:r=foo\n", "c-r-xfoo.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;x:r=\n", "c-r.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=foo\n\nBar.\nx:r=\n", "c-r.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=foo\n\nBar.\nx:r=\n", "c-r-xfoo.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=foo\n\nBar.\nx:r=bar\n", "c-r-xfoo.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=foo\n\nBar.\nx:r=bar\n", "c-r-xbar.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=foo\n\nBar.\nx:r=foo,bar\n", "c-r-xfoo.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=foo\n\nBar.\nx:r=foo,bar\n", "c-r-xbar-xfoo.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;a:r=foo\n", "c-r-afoo.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;a:r=foo\n\nBar.\na:r=\n", "c-r-afoo.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;a:r=foo\n\nBar.\na:r=\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;t=r\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;t=r\n", "c-r.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;t=r\n\nBar.\nt=none\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;c=r;t=r;e:r=t\n", "c-r-et.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;t=r;e:r=t\n", "c-r-et.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;e:r=m;t=r\n", "c-r-em.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;c=r;e:r=g;s=r\n", "c-r-eg-s.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;e:r=g;s=r\n", "c-r-eg-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\n\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\n\n", "c-r-s2.webp")]
	[DataRow("\"Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r\n\nBar.\ns=\n", "c-r-s.webp")]
	[DataRow("\"Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r\n\nBar.\ns=\n", "c-r-1.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r\n\n\"Foo.\"\n\n\nBar.\ns=\n", "c-r-s.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r\n\n\"Foo.\"\n\n\nBar.\ns=\n", "c-r-s2.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r\n\n\"Foo.\"\n\n\nBar.\ns=\n", "c-r-2.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r\n\n\"Foo.\"\n\n\nBar.\ns=;i:r=\n", "c-r.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r\n\n\"Foo.\"\ne:r=h\n\nBar.\ns=\n", "c-r-eh-s.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r\n\n\"Foo.\"\ne:r=h\n\nBar.\ns=\n", "c-r-eh-1.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r;e:r=u\n\n\"Foo.\"\n\n\nBar.\ns=\n", "c-r-eu-s.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r;e:r=u\n\n\"Foo.\"\n\n\nBar.\ns=\n", "c-r-eu-s2.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r;e:r=u\n\n\"Foo.\"\n\n\nBar.\ns=\n", "c-r-eu-2.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r;e:r=u\n\n\"Foo.\"\n\n\nBar.\ns=;i:r=\n", "c-r-eu.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;e:r=g;s=r\n\n\"Bar.\"\n\n", "c-r-eg-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;e:r=g;s=r\n\n\"Bar.\"\n\n", "c-r-eg-s2.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\ne:r=g\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\ne:r=g\n", "c-r-eg-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;e:r=g\n\n\"Bar.\"\ne:r=\n", "c-r-eg-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;e:r=g\n\n\"Bar.\"\ne:r=\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\nx:r=foo\n", "c-r-xfoo-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\na:r=foo\n", "c-r-afoo-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;x:r=foo\n\n\"Bar.\"\n\n", "c-r-xfoo-s2.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;a:r=foo\n\n\"Bar.\"\n\n", "c-r-afoo-s2.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;x:r=foo;e:r=g\n\n\"Bar.\"\n\n", "c-r-xfoo-eg-s2.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;a:r=foo;e:r=g\n\n\"Bar.\"\n\n", "c-r-afoo-eg-s2.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;e:r=g;s=r;a:r=foo;x:r=bar\n", "c-r-afoo-xbar-eg-s.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;e:r=g;s=r;a:r=foo;x:r=fizz,buzz\n", "c-r-afoo-xbuzz-xfizz-eg-s.webp")]
	[DataRow("\"Foo.\"\n\n\"Bar.\"\n\n\"Fizz.\"\n", "\"Foo.\"\nn:r=R;n:j=J;s=r;c=r,j\n\n\"Bar.\"\ns=j\n\n\"Fizz.\"\ns=r\n", "c-r-s2.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=bar\n\nBar.\nx:r=\n", "c-r-xbar.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;c=r;x:r=bar\n\nBar.\nx:r=\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;n:f=F;c=r,f\n", "c-r.webp")]
	[DataRow("Foo\n", "Foo\nn:r=R;n:f=F;c=r,f\n", "c-f.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;e:r=g;x:r=bar\n\nBar.\nr=p;c=r\n", "c-r.webp")]
	[DataRow("Foo. Bar.\n", "Foo.\nn:r=R;e:r=g;a:r=foo;x:r=bar\n\nBar.\nr=p;c=r\n", "c-r-afoo.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;e:r=g;s=r;a:r=foo;x:r=bar\n\n\"Bar.\"\nr=p;c=r\n", "c-r-afoo.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;e:r=g;a:r=foo;x:r=bar\n\n\"Bar.\"\nr=p;s=r\n", "c-r-afoo-s.webp")]
	[DataRow("Foo\n", "Foo\no=myobj\n", "o-myobj.webp")]
	[DataRow("Foo\n", "Foo\no=myobj\n", "class='c'")]
	[DataRow("Foo\n", "Foo\nb=p\n", "'p'")]
	[DataRow("Foo\n", "Foo\nr=p\n", "'p'")]
	[DataRow("“Foo” said Foo. “Bar.”\n", "“Foo” said Foo. “Bar.”\nn:f=Foo;s=f\n", "<span class='d'>“Foo”</span> said Foo. <span class='d'>“Bar.”</span>")]
	[DataRow("“Foo” said Foo. “Bar.”\n", "<span class='d'>“Foo”</span> said Foo. “Bar.”\nn:f=Foo;s=f\n", "<span class='d'>“Foo”</span> said Foo. “Bar.”")]
	[DataRow("Buzz. “Foo. ‘Bar. “Fizz.” Bar.’ Foo.” Buzz.\n", "Buzz. <span class='d'>“Foo. ‘Bar. “Fizz.” Bar.’ Foo.”</span> Buzz.\nn:f=Foo;s=f\n", "<span class='d'>“Foo. ‘Bar. “Fizz.” Bar.’ Foo.”</span>")]
	[DataRow("Buzz. “Foo. ‘Bar. “Fizz.” Bar.’ Foo.” Buzz.\n", "Buzz.\n\n\n“Foo.”\nn:f=Foo;s=f\n\n“‘Bar. “Fizz.” Bar.’ Foo.”\ng=b;n:b=Bar;s=b\n\nBuzz.\ng=;s=\n", "<span class='d'>‘Bar. “Fizz.” Bar.’</span>")]
	[DataRow("Buzz. “Foo. ‘Bar. “F’izz.” Bar.’ Foo.” Buzz.\n", "Buzz.\n\n\n“Foo.”\nn:f=Foo;s=f\n\n“‘Bar. “F’izz.” Bar.’ Foo.”\ng=b;n:b=Bar;s=b\n\nBuzz.\ng=;s=\n", "<span class='d'>‘Bar. “F’izz.” Bar.’</span>")]
	[DataRow("Buzz. “Foo. ‘Bar. “‘F’izz.” Bar.’ Foo.” Buzz.\n", "Buzz.\n\n\n“Foo.”\nn:f=Foo;s=f\n\n“<span class='d'>‘Bar. “‘F’izz.” Bar.’</span> Foo.”\ng=b;n:b=Bar;s=b\n\nBuzz.\ng=;s=\n", "<span class='d'>‘Bar. “‘F’izz.” Bar.’</span>")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo;v=110,120\n", "'width:110%;height:120%;'")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo;v=,120\n", "'height:120%;'")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo;v=110\n", "'width:110%;'")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo;v=110,,\n", "'width:110%;'")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo;v=110,120,40\n", "'width:110%;height:120%;top:40%;'")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo;v=,120,40\n", "'height:120%;top:40%;'")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo;v=,,40\n", "'top:40%;'")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:name=Name;s=name\n", "Name")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:name=Name;s=name;m=nospeaker\n", "Name")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:name=Name;s=name\n", "c-name-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\ni=3\n", "c-r-s3.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;t=r\n\n\"Bar.\"\ni=3\n", "c-r-3.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r\n\n\"Foo.\"\ne:r=h\n\nBar.\ns=;i:r=\n", "c-r-eh.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r\n\n\"Foo.\"\ne:r=h\n\nBar.\ns=;i:r=1\n", "c-r-eh-1.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r\n\n\"Foo.\"\ne:r=h\n\nBar.\ns=;i:r=2\n", "c-r-eh-2.webp")]
	[DataRow("\"Foo. Foo.\" Bar.\n", "\"Foo.\"\nn:r=R;s=r;c=r\n\n\"Foo.\"\ne:r=h\n\nBar.\ns=;i:r=3\n", "c-r-eh-3.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;i=2\n\n\"Bar.\"\ne:r=g\n", "c-r-s2.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r;i=2\n\n\"Bar.\"\ne:r=g\n", "c-r-eg-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\ne:r=g;i=2\n", "c-r-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\ne:r=g;i=2\n", "c-r-eg-s2.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;t=r\n\n\"Bar.\"\ne:r=g;i=2\n", "c-r.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;t=r\n\n\"Bar.\"\ne:r=g;i=2\n", "c-r-eg-2.webp")]
	[DataRow("\"Foo.\"\n\n\"Bar.\"\n\n\"Fizz.\"\n", "\"Foo.\"\nn:r=R;n:j=J;s=r;c=r,j;i=3\n\n\"Bar.\"\ns=j\n\n\"Fizz.\"\ns=r\n", "c-r-s3.webp")]
	[DataRow("\"Foo.\"\n\n\"Bar.\"\n\n\"Fizz.\"\n", "\"Foo.\"\nn:r=R;n:j=J;s=r;c=r,j;i:r=3\n\n\"Bar.\"\ns=j\n\n\"Fizz.\"\ns=r\n", "c-r-s3.webp")]
	[DataRow("\"Foo.\"\n\n\"Bar.\"\n\n\"Fizz.\"\n", "\"Foo.\"\nn:r=R;n:j=J;s=r;c=r,j;i:j=3\n\n\"Bar.\"\ns=j\n\n\"Fizz.\"\ns=r\n", "c-j-3.webp")]
	[DataRow("\"Foo.\"\n\n\"Bar.\"\n\n\"Fizz.\"\n", "\"Foo.\"\nn:r=R;n:j=J;s=r;c=r,j\n\n\"Bar.\"\ns=j;i=3\n\n\"Fizz.\"\ns=r\n", "c-j-s3.webp")]
	[DataRow("\"Foo.\"\n\n\"Bar.\"\n\n\"Fizz.\"\n", "\"Foo.\"\nn:r=R;n:j=J;s=r;c=r,j\n\n\"Bar.\"\ns=j;i:r=3\n\n\"Fizz.\"\ns=r\n", "c-r-3.webp")]
	[DataRow("\"Foo.\"\n\n\"Bar.\"\n\n\"Fizz.\"\n", "\"Foo.\"\nn:r=R;n:j=J;s=r;c=r,j\n\n\"Bar.\"\ns=j;i:j=3\n\n\"Fizz.\"\ns=r\n", "c-j-s3.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;e:r=g;s=r;e:r=z\n", "c-r-ez-s.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;e:r=g;i=2;s=r;i=3\n", "c-r-eg-s3.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;c=r;e:r=g;i:r=2;e:r=x;i:r=1\n", "c-r-ex-1.webp")]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:r=R;c=r;e:r=g;i:r=2;e:r=x;i:r=\n", "c-r-ex.webp")]
	[DataRow("Foo. Bar.\n\nFizz. Buzz.\n", "Foo. Bar.\n\n\nFizz.\n\n\nBuzz.\n\n", "<div>Foo. Bar.</div>")]
	[DataRow("Foo. Bar.\n\nFizz. Buzz.\n", "Foo. Bar.\n\n\nFizz.\n\n\nBuzz.\n\n", "<div>Fizz.</div>")]
	[DataRow("Foo.<br>Bar.\n\nFizz. Buzz.\n", "Foo.<br>Bar.\n\n\nFizz.\n\n\nBuzz.\n\n", "<div class='titletext center'><span>Foo.</span><br><span>Bar.</span></div>")]
	[DataRow("Foo.<br>Bar.\n\nFizz. Buzz.\n", "Foo.<br>Bar.\n\n\nFizz.\n\n\nBuzz.\n\n", "<div>Buzz.</div>")]
	[DataRow("Foo\n", "Foo\nb=foo;f:b:foo=blur(5px)\n", "blur(calc(5 / 15 * var(--vwUnit)))")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo;f:c:foo=blur(3px)\n", "blur(calc(3 / 15 * var(--vwUnit)))")]
	[DataRow("Foo\n", "Foo\nb=foo;f:b:foo=brightness(85%) blur(5px)\n", "brightness(85%) blur(calc(5 / 15 * var(--vwUnit)))")]
	[DataRow("Foo\n", "Foo\nb=foo;f:b:foo=blur(5px) brightness(85%)\n", "blur(calc(5 / 15 * var(--vwUnit))) brightness(85%)")]
	[DataRow("Foo\n", "Foo\nb=foo;f=lightning\n", "'foo;;lightning'")]
	[DataRow("## Foo Bar\n", "## Foo Bar\n\n", "2|Foo Bar")]
	[DataRow("## Foo<br>Bar\n", "## Foo<br>Bar\n\n", "2|Foo: Bar")]
	[DataRow("Foo. Bar.\n", "Foo.<f>Footnote.</f> Bar.\n\n", "Foo.<sup>†</sup>")]
	[DataRow("Foo. Bar.\n", "Foo.<f>Footnote.</f> Bar.\n\n", "<p class='f'><sup>†</sup>Footnote.</p>")]
	[DataRow("“Foo. Bar.”\n", "“Foo.<f>Footnote.</f> Bar.”\n\n", "Foo.<sup>†</sup>")]
	[DataRow("“Foo. Bar.”\n", "“Foo.<f>Footnote.</f> Bar.”\n\n", "<p class='f'><sup>†</sup>Footnote.</p>")]
	[DataRow("“Foo. Bar.”\n", "“Foo.<f>Footnote.</f> Bar.”\n\n", "<span class='d'")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2;b=b2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "<span class='d'>“Foo.”</span>")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2;b=b2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "“<span class='d'>‘Bar.’</span>”")]
	[DataRow("“Foo. ‘Bar,’ bar.”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar,’ bar.”\ng=b2;s=s2;b=b2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "“<span class='d'>‘Bar,’</span> bar.”")]
	[DataRow("“Foo. ‘Bar,’ bar, ‘bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar,’ bar, ‘bar.’”\ng=b2;s=s2;b=b2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "“<span class='d'>‘Bar,’</span> bar, <span class='d'>‘bar.’</span>”")]
	[DataRow("“Foo. ‘Bar “bar” bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar “bar” bar.’”\ng=b2;s=s2;b=b2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "“<span class='d'>‘Bar “bar” bar.’</span>”")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2;b=b2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "“‘<span class='d'>“Fizz.”</span>’”")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz,” fizz.’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2;b=b2\n\n“‘“Fizz,” fizz.’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "“‘<span class='d'>“Fizz,”</span> fizz.’”")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz,” fizz, “fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2;b=b2\n\n“‘“Fizz,” fizz, “fizz.”’”\n;g=b3;s=s3;b=b3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "“‘<span class='d'>“Fizz,”</span> fizz, <span class='d'>“fizz.”</span>’”")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2\n\n“‘“Fizz.”’”\n;g=b3;s=s3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "'b2'")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2\n\n“‘“Fizz.”’”\n;g=b3;s=s3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "'b3'")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1;x:s1=foo;e:s1=bar;\n\n“‘Bar.’”\ng=b2;s=s2\n\n“‘“Fizz.”’”\n;g=b3;s=s3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "'c-s1-xfoo-ebar-s.webp']")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2\n\n“‘“Fizz.”’”\n;g=b3;s=s3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "c-s2-s.webp']")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2;i=3\n\n“‘“Fizz.”’”\n;g=b3;s=s3\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "'c-s2-s3.webp']")]
	[DataRow("“Foo. ‘Bar.’”\n\n“‘“Fizz.”’”\n\n“‘“Buzz.”’”\n\n“‘Bar.’ Foo.”\n", "“Foo.”\nn:s1=S;n:s2=S;n:s3=S;s=s1;b=b1\n\n“‘Bar.’”\ng=b2;s=s2\n\n“‘“Fizz.”’”\n;g=b3;s=s3;e:s3=inner\n\n“‘“Buzz.”’”\n\n\n“‘Bar.’”\ng=;\n\n“Foo.”\ng=\n", "c-s3-einner-s2.webp")]
	[DataRow("Foo. Foo. “Bar1. Bar2.” Foo.\n", "Foo.\nb=b1\n\nFoo.\n\n\n“Bar1.”\nn:b=B;s=b\n\n“Bar2.”\ng=b2\n\nFoo.\ng=;s=\n", "<span class='d'>“Bar1")]
	[DataRow("Foo. Foo. “Bar1. Bar2.” Foo.\n", "Foo.\nb=b1\n\nFoo.\n\n\n“Bar1.”\ng=b2;n:b=B;s=b\n\n“Bar2.”\ns=\n\nFoo.\ng=\n", "<span class='d'>“Bar1")]
	[DataRow("Foo. Foo. “Bar1. Bar2.” Foo.\n", "Foo.\nb=b1\n\nFoo.\n\n\n“Bar1.”\ng=b2;n:b=B\n\n“Bar2.”\ns=b\n\nFoo.\ns=;g=\n", "<span class='d'>“Bar2")]
	[DataRow("Foo. Foo. “Bar0. Bar1. Bar2.” Foo.\n", "Foo.\nb=b1\n\nFoo.\n\n\n“Bar0.”\ng=b2;n:b=B;s=b\n\n“Bar1.”\n\n\n“Bar2.”\ne:b=happy\n\nFoo.\ng=;s=\n", "c-b-ehappy-s")]
	[DataRow("Foo. Foo. “Bar0. Bar1. ‘Bar2.’” Foo.\n", "Foo.\nb=b1\n\nFoo.\n\n\n“Bar0.”\n;n:b=B;s=b\n\n“Bar1.”\n;g=b2\n\n“‘Bar2.’”\ns=b;e:b=happy\n\nFoo.\ng=;s=\n", "c-b-ehappy-s")]
	[DataRow("Foo. Foo. “Bar1. Bar2.” Foo.\n", "Foo.\nb=b1\n\nFoo.\n\n\n“Bar1.”\ng=b2\n\n“Bar2.”\n\n\nFoo.\ng=\n", "['b1','b2;;fade','b2','b1;;fade']")]
	public void Compiler_BuildHtml_ContainsHtml(string rawText, string pulpText, string htmlSnippet) {
		string html = Compiler.BuildHtml(rawText, pulpText);
		Assert.Contains(htmlSnippet, html);
	}

	[TestMethod]
	[DataRow("\"Foo\"\n", "\"Foo\"\nn:name=Name;s=name;m=nospeaker\n", "c-name-s.webp")]
	[DataRow("\"Foo. Bar.\"\n", "\"Foo.\"\nn:r=R;s=r\n\n\"Bar.\"\ni=\n", "c-r-s2.webp")]
	[DataRow("\"Foo.\"\n\n\"Bar.\"\n\n\"Fizz.\"\n", "\"Foo.\"\nn:r=R;n:j=J;s=r;c=r,j;i=3\n\n\"Bar.\"\ns=j\n\n\"Fizz.\"\ns=r\n", "c-j-3.webp")]
	[DataRow("\"Foo.\"\n\n\"Bar.\"\n\n\"Fizz.\"\n", "\"Foo.\"\nn:r=R;n:j=J;s=r;c=r,j;i:r=3\n\n\"Bar.\"\ns=j\n\n\"Fizz.\"\ns=r\n", "c-j-3.webp")]
	[DataRow("\"Foo.\"\n\n\"Bar.\"\n\n\"Fizz.\"\n", "\"Foo.\"\nn:r=R;n:j=J;s=r;c=r,j;i:j=3\n\n\"Bar.\"\ns=j\n\n\"Fizz.\"\ns=r\n", "c-r-s3.webp")]
	[DataRow("Foo\n", "Foo\nb=foo;f:b:foo=blur(5px)\n", "blur(5px)")]
	[DataRow("Foo\n", "Foo\nn:foo=Foo;c=foo;f:c:foo=blur(5px)\n", "blur(5px)")]
	[DataRow("Foo\n", "Foo<e>Book: <book>Wisconsin Death Trip|the book</book></e>\n\n", ">Wisconsin</a>")]
	[DataRow("Foo. Foo. “Bar1. Bar2.” Foo.\n", "Foo.\nb=b1\n\nFoo.\n\n\n“Bar1.”\nn:b=B;s=b\n\n“Bar2.”\ng=b2\n\nFoo.\ng=;s=\n", "<span class='d'>“Bar2")]
	[DataRow("Foo. Foo. “Bar0. Bar1. Bar2.” Foo.\n", "Foo.\nb=b1\n\nFoo.\n\n\n“Bar0.”\n;n:b=B;s=b\n\n“Bar1.”\n;g=b2\n\n“Bar2.”\ne:b=happy\n\nFoo.\ng=;s=\n", "c-b-ehappy-s")]
	[DataRow("Foo. Foo. “Bar0. Bar1. ‘Bar2.’” Foo.\n", "Foo.\nb=b1\n\nFoo.\n\n\n“Bar0.”\n;n:b=B;s=b\n\n“Bar1.”\n;g=b2\n\n“‘Bar2.’”\ne:b=happy\n\nFoo.\ng=;s=\n", "c-b-ehappy-s")]
	public void Compiler_BuildHtml_DoesNotContainsHtml(string rawText, string pulpText, string htmlSnippet) {
		string html = Compiler.BuildHtml(rawText, pulpText);
		Assert.DoesNotContain(htmlSnippet, html);
	}

	[TestMethod]
	public void Compiler_BuildHtml_Wizard() {
		string directory = Directory.GetCurrentDirectory().Substring(0, Directory.GetCurrentDirectory().IndexOf("/Pulpifier/", StringComparison.Ordinal)) + "/Pulpifier/examples/wizard/";
		string json = File.ReadAllText(Path.Combine(directory, "metadata.json"));
		Metadata metadata = Metadata.Parse(json);
		Assert.AreEqual("Wizard", metadata.Title);

		string book = File.ReadAllText(Path.Combine(directory, "book.txt"));
		string pulp = File.ReadAllText(Path.Combine(directory, "pulp.txt"));
		Compiler.BuildHtml(book, pulp, out Dictionary<string, ImageMetadata> files);
		CollectionAssert.AreEquivalent(files.Keys, new List<string> { "o-apple", "c-wizard-s", "c-wizard-s2", "c-wizard-s3", "c-hofstadter", "b-b1", "b-b2", "b-b3" });
	}
}